### ISSUE TITLE
[init] 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [TeamShortWeather/ShortWeather-AOS#1]
## Issue 📌

초기 세팅

## Todo 📝

- [x]  .gitignore 파일 추가
- [x]  issue & pull request 템플릿 추가
- [x]  label 만들기
- [x]  초기 프로젝트 추가
- [x]  dependency 추가
- [x]  패키지 나누기 ( Sample naming으로 dummy 추가)
- [x] 확장 함수 추가
- [x]  color & font & text 정의
- [x] pull request 1명 이상 승인 필요하게 지정
