### ISSUE TITLE
[ui] 오늘 날씨 UI 구현

### ISSUE THREAD

**Issue by hwangsunwoong** [TeamShortWeather/ShortWeather-AOS#11]
## Issue 📌
오늘 날씨 UI 구현

## Todo 📝
- [x] 오늘 날씨 초안 UI 구현
- [x] 맞춤 날씨 초안 UI 구현
- [x] 오늘 날씨 상단 -> 하단 스와이프 UI 구현
