### ISSUE TITLE
[ui] 맞춤 날씨 UI 추가 구현

### ISSUE THREAD

**Issue by hwangsunwoong** [TeamShortWeather/ShortWeather-AOS#27]
## Issue 📌
맞춤 날씨 UI 추가 구현

## Todo 📝
- [x] 맞춤 날씨 UI 추가 구현
- [x] 날씨 & 강수 item UI 구현
- [x] 더미 데이터 테스트 로직 구현
- [x] 미세먼지 item UI 제거
