### ISSUE TITLE
[fix] 서버통신 대비 viewModel 개편

### ISSUE THREAD

**Issue by win-luck** [TeamShortWeather/ShortWeather-AOS#45]
## Issue 📌
서버통신 대비 viewModel 로직 개편, 데이터 클래스 생성
## Todo 📝
- [x] viewModel setter 추가
- [x] viewModel 서버통신 관련 기초 함수 추가
- [x] request, response 관련 데이터 클래스 생성
