### ISSUE TITLE
[ui] 오늘 날씨 Toast UI & 기능 구현

### ISSUE THREAD

**Issue by hwangsunwoong** [TeamShortWeather/ShortWeather-AOS#47]
## Issue 📌
오늘 날씨 Toast UI & 기능 구현

## Todo 📝
- [x] 오늘 날씨 Toast UI 구현
- [x] 더미 데이터 구현
- [x] 오늘 날씨 Toast 기능 구현
