### ISSUE TITLE
[feat] 유저조회/정보입력 서버통신 구현

### ISSUE THREAD

**Issue by win-luck** [TeamShortWeather/ShortWeather-AOS#49]
## Issue 📌
유저조회, 정보입력 서버통신 구현 by Coroutine && Hilt
## Todo 📝
- [x] 서버통신 관련 viewModel 개편
- [x] 유저조회 서버통신 구현 -> 조회 결과에 따라 스플래쉬에서 액티비티 분기처리
- [x] 정보입력 서버통신 구현
