### ISSUE TITLE
[fix] 서버통신 상태별 로직 수정

### ISSUE THREAD

**Issue by win-luck** [TeamShortWeather/ShortWeather-AOS#67]
## Issue 📌
스플래쉬 화면, 정보입력 화면 서버통신 상태별 로직 수정
## Todo 📝
* 스플래쉬 화면
- [x] 200이면서 이미 존재하는 유저 -> MainActivity로 이동
- [x] 200이면서 처음 등록하는 유저 -> InfoInputActivity로 이동
- [x] 400, 500 -> 토스트 메시지 출력
- [x] HTTP 접근 실패 -> 토스트 메시지 출력
* 정보입력 화면
- [x] 200-> MainActivity로 이동
- [x] 400, 500 -> 토스트 메시지 출력
- [x] HTTP 접근 실패 -> 토스트 메시지 출력
