### ISSUE TITLE
[feat] 정보입력 기능 구현

### ISSUE THREAD

**Issue by win-luck** [TeamShortWeather/ShortWeather-AOS#7]
## Issue 📌
정보 입력 화면 로직 구현 및 타임피커 추가
## Todo 📝
- [x] 1페이지 바텀시트 리사이클러뷰 구현
- [x] 1페이지 바텀시트에서 아이템 선택 시 화면에 삽입
- [x] 1페이지 정보입력이 없을 때 빨강색, 정보입력이 성공했을 때 파랑색 하이라이트 구현
- [x] 2페이지 타임피커 구현
- [x] 2페이지 시간입력이 없을 때 빨강색, 시간입력이 성공했을 때 파랑색 하이라이트 구현
